app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, BooleanField, \
    SelectField
from wtforms.validators import Length, DataRequired, Email, Regexp, \
    ValidationError

from app.models import User
from app.auth.forms import cities

roles = [('ACCESS', ' Normal User'), ('ADMIN', ' Administrator')]


class EditProfileForm(FlaskForm):
    name = StringField('Real Name', validators=[Length(0, 64)])
    location = SelectField('Where are you from?', choices=cities)
    about_me = TextAreaField('About Me')
    submit = SubmitField('Update')


class EditProfileAdminForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Length(1, 64), Email()])
    username = StringField('Username',
                           validators=[DataRequired(), Length(1, 64),
                                       Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                              'Username must start with a letter and have only letters, numbers, dots or underscores')])
    is_confirmed = BooleanField('Account Confirmed?')
    role = SelectField('Modify Role (Privilege)', choices=roles)
    name = StringField('Real Name', validators=[Length(0, 64)])
    location = SelectField('Where are you from?', choices=cities)
    about_me = TextAreaField('About Me')
    submit = SubmitField('Update')

    """
    sort in PyMongo: Collection.find().sort([('key1',1),('key2',-1), ...]).limit(<value>)
         1 for ascending sort
        -1 for descending sort
         limit() for getting first <value> documents from the sort result

    sort in MongoShell: Collection.find().sort({key1:1, key2:-1, ...}).limit(<value>)
    """

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        # self.role.choices = [(str(r.get('_id')), r.get('type')) for r in\
        #                      db.Role.find({'type': {'$ne': '_timestamp'}}).sort([('type', -1)])]
        self.user = user

    def validate_email(self, field):
        user_in_db = User.search({'email': field.data})
        if user_in_db and str(user_in_db.get('_id')) != self.user.id:
            raise ValidationError('Email already registered by another user.')

    def validate_username(self, field):
        user_in_db = User.search({'username': field.data})
        if user_in_db and str(user_in_db.get('_id')) != self.user.id:
            raise ValidationError(
                'Username already registered by another user.')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
import json
import os
from flask import render_template, redirect, url_for, request, abort, flash
from flask_login import current_user, login_required
from bson import ObjectId

from . import main
from .forms import EditProfileForm, EditProfileAdminForm
from app.models import UserUtl, Snippet
from app.decorators import admin_required
from app.models import User
from common.general import random_word
from common.db import acquire_db_summary, drop_db, empty_collection, \
    mongo_connect
from crawlers.loader import CrawlerLoader


@main.route('/test')
def test():
    """
    test page, feature test only
    """
    return render_template('test.html')


@main.route('/', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        return render_template('index.html',
                               company=current_user.company.upper())
    else:
        return redirect(url_for('auth.login'))


@main.route('/user_profile/<id>')
def user(id):
    user_dict = User.search({'_id': ObjectId(id)})
    if not user_dict:
        return render_template('errors/missing_user.html')
    user_utl = UserUtl(user_dict)

    return render_template('main/user_profile.html', user_utl=user_utl)


@main.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        User.update_doc({'email': current_user.email},
                        {
                            'name': form.name.data,
                            'location': form.location.data,
                            'about_me': form.about_me.data
                        })
        flash('Your profile has been updated successfully.', category='info')
        return redirect(url_for('main.user', id=current_user.id))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('main/edit_profile.html', form=form,
                           user_utl=current_user)


@main.route('/admin_edit_profile/<id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user_dict = User.search({'_id': ObjectId(id)})
    if not user_dict:
        abort(404)
    user_utl = UserUtl(user_dict)
    form = EditProfileAdminForm(user=user_utl)
    if form.validate_on_submit():
        User.update_doc({'email': user_dict.get('email')},
                        {'email': form.email.data,
                         'username': form.username.data,
                         'is_confirmed': form.is_confirmed.data,
                         'role': form.role.data,
                         'name': form.name.data,
                         'location': form.location.data,
                         'about_me': form.about_me.data
                         })
        flash('The profile has been updated successfully.', category='info')
        return redirect(url_for('main.user', id=user_utl.id))
    form.email.data = user_utl.email
    form.username.data = user_utl.username
    form.is_confirmed.data = user_utl.is_confirmed
    form.role.data = user_utl.role.type
    form.name.data = user_utl.name
    form.location.data = user_utl.location
    form.about_me.data = user_utl.about_me
    return render_template('main/edit_admin_profile.html', form=form,
                           user_utl=user_utl)


@main.route('/create_snippet', methods=['GET', 'POST'])
@login_required
def create_snippet():
    if request.form:
        snippet_code = request.form.get('code')
        snippet_group = request.form.get('group')
        snippet_scenario = request.form.get('scenario')
        group_id, scenario_id = Snippet(snippet_group, snippet_scenario,
                                        snippet_code).new()

        if group_id and scenario_id:
            flash('New code snippet has been created successfully.',
                  category='success')
            return redirect(url_for('main.edit_snippet', group=snippet_group,
                                    scenario=snippet_scenario))
        else:
            flash(
                'Naming conflict, please change Group name or Scenario name.',
                category='danger')
            return render_template('main/create_snippet.html',
                                   snippet_code=snippet_code)
    return render_template('main/create_snippet.html', snippet_code='')


@main.route('/edit_snippet/<group>/<scenario>', methods=['GET', 'POST'])
@login_required
def edit_snippet(group, scenario):
    old_group_dict = Snippet.search_group({'name': group})
    if not old_group_dict:
        try:
            old_group_dict = Snippet.search_group({'_id': ObjectId(group)})
        except:
            abort(404)

    old_scenario_id_list = old_group_dict.get('scenarios')
    old_scenario_dict = {}
    old_scenario_id = ''
    old_scenario = scenario
    for _id in old_scenario_id_list:
        old_scenario_dict = Snippet.search_scenario({'_id': ObjectId(_id)})
        if old_scenario_dict.get('name') == scenario:
            old_scenario_id = _id
            break

    if not old_scenario_dict or not old_scenario_id:
        try:
            old_scenario_dict = Snippet.search_scenario(
                {'_id': ObjectId(scenario)})
            old_scenario = old_scenario_dict.get('name')
            old_scenario_id = scenario
        except:
            abort(404)

    old_code = old_scenario_dict.get('code')
    old_group = old_group_dict.get('name')
    group_id = str(old_group_dict.get('_id'))

    if request.form:
        new_code = request.form.get('code')
        new_group = request.form.get('group')
        new_scenario = request.form.get('scenario')

        if old_group_dict.get('name') != new_group:
            # case 1: group changed
            # remove old scenario id from old group, if scenario list after
            # the operation is empty, delete the group
            old_scenario_id_list.remove(old_scenario_id)

            if not len(old_scenario_id_list):
                # if group has no scenario anymore after the removal, delete
                # the group directly
                Snippet.delete_doc_group({'_id': ObjectId(group_id)})
            else:
                # otherwise update group's scenario list
                Snippet.update_doc_group({'_id': ObjectId(group_id)},
                                         {'scenarios': old_scenario_id_list})

            new_group_dict = Snippet.search_group({'name': new_group})
            if new_group_dict:
                # if new target group already exists
                # before group change, check whether old/new scenario name is
                # already in target group, if conflict exists then do a rename
                new_scenario_id_list = Snippet.search_group(
                    {'_id': ObjectId(new_group_dict.get('_id'))}).get(
                    'scenarios')

                if old_scenario != new_scenario:
                    # if scenario name changed, check new scenario name
                    # conflict
                    for _id in new_scenario_id_list:
                        if Snippet.search_scenario({'_id': ObjectId(_id)}).get(
                                'name') == new_scenario:
                            new_scenario = f'{new_scenario}_{random_word(size=4)}'
                            flash(
                                'A naming conflict occurs to Scenario\'s name in current Group. Current Scenario has been renamed by a suffix.',
                                category='danger')
                            break
                else:
                    # if scenario name unchanged, check old scenario name
                    # conflict
                    for _id in new_scenario_id_list:
                        if Snippet.search_scenario({'_id': ObjectId(_id)}).get(
                                'name') == old_scenario:
                            new_scenario = f'{old_scenario}_{random_word(size=4)}'
                            flash(
                                'A naming conflict occurs to Snippet Scenario in current Group. Current Snippet Scenario has been renamed by a suffix.',
                                category='danger')
                            break

                # move old scenario id to new group, update group_id, update
                # scenario's group name
                Snippet.update_doc_group({'name': new_group},
                                         {'scenarios': old_scenario_id})

            else:
                # target new group does not exist
                # create new group with the old scenario id, update group_id
                document = {
                    'name': new_group,
                    'scenarios': [old_scenario_id]
                }
                Snippet.new_group(document)
            Snippet.update_doc_scenario({'_id': ObjectId(old_scenario_id)},
                                        {'name': new_scenario,
                                         'group': new_group})

        elif old_scenario != new_scenario:
            # case 2: group not changed but scenario changed
            # if group not changed but scenario changed, check new scenario
            # naming conflict under current group
            scenario_id_list = Snippet.search_group(
                {'_id': ObjectId(group_id)}).get('scenarios')
            for _id in scenario_id_list:
                if Snippet.search_scenario({'_id': ObjectId(_id)}).get(
                        'name') == new_scenario:
                    new_scenario = f'{new_scenario}_{random_word(size=4)}'
                    flash(
                        'A naming conflict occurs to Snippet Scenario in current Group. Current Snippet Scenario has been renamed by a suffix.',
                        category='danger')
                    break
            Snippet.update_doc_scenario({'_id': ObjectId(old_scenario_id)},

app/templates/main/create_snippet.html
{% extends "base.html" %}

{% block title %}Create Snippet{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block navbar_items %}
    {% if current_user.is_authenticated and current_user.is_confirmed%}
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.create_snippet') }}" style="font-family: Centaur;font-size: 20px;">Create Snippet</a></li>
        </ul>
    {% endif %}
{% endblock %}

{% block narrow_content %}
    <div class="row" style="height: 94vh">
        <div class="col-md-10" style="height: 99%">
            <div id="snippet-section" style="height: 100%">{{ snippet_code }}</div>
        </div>
        <div class="col-md-2">
            {% if current_user.is_authenticated %}
                <form id="snippet-form" method="POST">
                    <label style="font-size:15px">Snippet Group</label>
                    <input id="snippet-group" name="group" type="text" class="form-control">
                    <label style="font-size:15px">Snippet Scenario Name</label>
                    <input id="snippet-scenario" name="scenario" type="text" class="form-control">
                    <button class="btn btn-info" name="create" id="create-snippet">Create Snippet</button>
                </form>
            {% endif %}
            <br>
            <label for="syntax">Syntax</label>
            <select class="selectpicker" id="syntax" data-width="75%">
                <option value="python" selected="selected">XPLAN</option>
                <option value="html">HTML</option>
            </select>

            <label for="theme">Theme</label>
            <select class="selectpicker" id="theme" data-width="75%">
                <optgroup label="Bright">
                    <option value="github">GitHub</option>
                    <option value="solarized_light">Solarized Light</option>
                    <option value="xcode">XCode</option>
                </optgroup>
                <optgroup label="Dark">
                    <option value="chaos" selected="selected">Chaos</option>
                    <option value="monokai">Monokai</option>
                    <option value="pastel_on_dark">Pastel on Dark</option>
                    <option value="solarized_dark">Solarized Dark</option>
                </optgroup>
            </select>

            <label for="font-family">Font Family</label>
            <select class="selectpicker" id="font-family" data-width="75%">
                <option value="arial">Arial</option>
                <option value="consolas" selected="selected">Consolas</option>
                <option value="courier">Courier</option>
            </select>

            <label for="font-size">Font Size</label>
            <select class="selectpicker" id="font-size" data-width="75%">
                <option>12</option>
                <option>14</option>
                <option>16</option>
                <option>18</option>
                <option selected="selected">20</option>
                <option>22</option>
                <option>24</option>
                <option>28</option>
                <option>34</option>
                <option>40</option>
            </select>

            <div class="checkbox">
                <label><input id="show-invisibles" type="checkbox" value="" checked="checked">&nbsp&nbspShow Invisibles</label>
            </div>
            <div class="checkbox">
                <label><input id="wrap-text" type="checkbox" value="" checked="checked">&nbsp&nbspWrap Text</label>
            </div>

        </div>
    </div>
{% endblock %}

{% block page_script %}
    <script>
        var show_invisibles = true;
        var wrap_text = true;
        var initial_syntax = $('#syntax option:selected').val();
        var initial_theme = $('#theme option:selected').val();
        var initial_font_size = $('#font-size option:selected').val();
        var initial_font_family = $('#font-family option:selected').val();
        var code_section = ace.edit("snippet-section");
        code_section.setTheme("ace/theme/" + initial_theme);
        code_section.session.setMode("ace/mode/" + initial_syntax);
        code_section.setOption("showInvisibles", show_invisibles);
        code_section.setOption("fontFamily", initial_font_family);
        code_section.setOption("fontSize", parseInt(initial_font_size));
        code_section.getSession().setUseWrapMode(wrap_text);
        code_section.setShowPrintMargin(false);
        code_section.setBehavioursEnabled(true);

        // syntax dropdown
        $('#syntax').on('change', function(){
            code_section.session.setMode("ace/mode/" + $('#syntax').val());
        });
        // theme dropdown
        $('#theme').on('change', function(){
            code_section.setTheme("ace/theme/" + $('#theme').val());
        });
        // font dropdown
        $('#font-family').on('change', function(){
            code_section.setOption("fontFamily", $('#font-family').val());
        });
        // dont size dropdown
        $('#font-size').on('change', function(){
            code_section.setOption("fontSize", parseInt($('#font-size').val()));
        });
        // show invisibles tick
        $('#show-invisibles').click(function() {
            show_invisibles = this.checked;
            if(show_invisibles) {
                code_section.setOption("showInvisibles", true);
            }
            else {
                code_section.setOption("showInvisibles", false);
            }
        });
        // wrap text tick
        $('#wrap-text').click(function() {
            wrap_text = this.checked;
            if(wrap_text) {
                code_section.getSession().setUseWrapMode(wrap_text);
            }
            else {
                code_section.getSession().setUseWrapMode(wrap_text);
            }
        });

        $(document).ready(function() {
            function validate(fields) {
                var success = true;
                fields.forEach(function (field) {
                    if (!field.val()) {
                        success = false;
                    }
                });
                return success;
            }

            $('#create-snippet').on('click', function () {
                if (!validate([$('#snippet-group'), $('#snippet-scenario')])) {
                    return false;
                }
                else {
                    snippet_form = $('#snippet-form');
                    snippet_form.attr('action', '/create_snippet');
                    $('<input type="hidden" name="code"/>').val(code_section.getValue()).appendTo('#snippet-form');
                    snippet_form.submit();
                }
            });
        });
    </script>
{% endblock %}

app/templates/main/edit_admin_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Edit Profile{% endblock %}

{% block narrow_content %}
    <div class="page-header">
        {% if user_utl.id == current_user.id %}
            <h1>&lt;/ Modify Your Admin Profile&gt;</h1>
        {% else %}
            <h1>&lt;/ Modify Profile (Admin)&gt;</h1>
        {% endif %}
    </div>
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/templates/main/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Edit Profile{% endblock %}

{% block narrow_content %}
    <div class="page-header">
        {% if user_utl.id == current_user.id %}
            <h1>&lt;/ Edit Profile&gt;</h1>
        {% else %}
            <h1>&lt;/ Modify Profile (Admin)&gt;</h1>
        {% endif %}
    </div>
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/templates/main/edit_snippet.html
{% extends "base.html" %}

{% block title %}Edit Snippet{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block navbar_items %}
    {% if current_user.is_authenticated and current_user.is_confirmed%}
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.create_snippet') }}" style="font-family: Centaur;font-size: 20px;">Create Snippet</a></li>
        </ul>
    {% endif %}
{% endblock %}

{% block narrow_content %}
    <div class="row" style="height: 94vh">
        <div class="col-md-10" style="height: 99%">
            <div id="snippet-section" style="height: 100%">{{ snippet_code }}</div>
        </div>
        <div class="col-md-2">
            {% if current_user.is_authenticated %}
                <form id="snippet-form" method="POST">
                    <label style="font-size:15px">Snippet Group</label>
                    <input id="snippet-group" name="group" type="text" class="form-control" value="{{ snippet_group }}">
                    <label style="font-size:15px">Snippet Scenario Name</label>
                    <input id="snippet-scenario" name="scenario" type="text" class="form-control" value="{{ snippet_scenario }}">
                    <button class="btn btn-info" name="edit" id="save-snippet" style="width:45%">Save</button>
                    <button class="btn btn-danger" name="delete" id="delete-snippet" style="width:45%" data-toggle="modal" data-target="#_notification">Delete</button>
                </form>
            {% endif %}
            <br>
            <label for="syntax">Syntax</label>
            <select class="selectpicker" id="syntax" data-width="75%">
                <option value="python" selected="selected">XPLAN</option>
                <option value="html">HTML</option>
            </select>

            <label for="theme">Theme</label>
            <select class="selectpicker" id="theme" data-width="75%">
                <optgroup label="Bright">
                    <option value="github">GitHub</option>
                    <option value="solarized_light">Solarized Light</option>
                    <option value="xcode">XCode</option>
                </optgroup>
                <optgroup label="Dark">
                    <option value="chaos" selected="selected">Chaos</option>
                    <option value="monokai">Monokai</option>
                    <option value="pastel_on_dark">Pastel on Dark</option>
                    <option value="solarized_dark">Solarized Dark</option>
                </optgroup>
            </select>

            <label for="font-family">Font Family</label>
            <select class="selectpicker" id="font-family" data-width="75%">
                <option value="arial">Arial</option>
                <option value="consolas" selected="selected">Consolas</option>
                <option value="courier">Courier</option>
            </select>

            <label for="font-size">Font Size</label>
            <select class="selectpicker" id="font-size" data-width="75%">
                <option>12</option>
                <option>14</option>
                <option>16</option>
                <option>18</option>
                <option selected="selected">20</option>
                <option>22</option>
                <option>24</option>
                <option>28</option>
                <option>34</option>
                <option>40</option>
            </select>

            <div class="checkbox">
                <label><input id="show-invisibles" type="checkbox" value="" checked="checked">&nbsp&nbspShow Invisibles</label>
            </div>
            <div class="checkbox">
                <label><input id="wrap-text" type="checkbox" value=""  checked="checked">&nbsp&nbspWrap Text</label>
            </div>

        </div>
    </div>
{% endblock %}

{% block page_script %}
    <script>
        var show_invisibles = true;
        var wrap_text = true;
        var initial_syntax = $('#syntax option:selected').val();
        var initial_theme = $('#theme option:selected').val();
        var initial_font_size = $('#font-size option:selected').val();
        var initial_font_family = $('#font-family option:selected').val();
        var code_section = ace.edit("snippet-section");
        code_section.setTheme("ace/theme/" + initial_theme);
        code_section.session.setMode("ace/mode/" + initial_syntax);
        code_section.setOption("showInvisibles", show_invisibles);
        code_section.setOption("fontFamily", initial_font_family);
        code_section.setOption("fontSize", parseInt(initial_font_size));
        code_section.getSession().setUseWrapMode(wrap_text);
        code_section.setShowPrintMargin(false);
        code_section.setBehavioursEnabled(true);

        // syntax dropdown
        $('#syntax').on('change', function(){
            code_section.session.setMode("ace/mode/" + $('#syntax').val());
        });
        // theme dropdown
        $('#theme').on('change', function(){
            code_section.setTheme("ace/theme/" + $('#theme').val());
        });
        // font dropdown
        $('#font-family').on('change', function(){
            code_section.setOption("fontFamily", $('#font-family').val());
        });
        // dont size dropdown
        $('#font-size').on('change', function(){
            code_section.setOption("fontSize", parseInt($('#font-size').val()));
        });
        // show invisibles tick
        $('#show-invisibles').click(function() {
            show_invisibles = this.checked;
            if(show_invisibles) {
                code_section.setOption("showInvisibles", true);
            }
            else {
                code_section.setOption("showInvisibles", false);
            }
        });
        // wrap text tick
        $('#wrap-text').click(function() {
            wrap_text = this.checked;
            if(wrap_text) {
                code_section.getSession().setUseWrapMode(wrap_text);
            }
            else {
                code_section.getSession().setUseWrapMode(wrap_text);
            }
        });

        $(document).ready(function() {
            var group_backup = $('#snippet-group').val();
            var scenario_backup = $('#snippet-scenario').val();

            function validate(fields) {
                var success = true;
                fields.forEach(function (field) {
                    if (!field.val()) {
                        success = false;
                    }
                });
                return success;
            }

            $('#save-snippet').on('click', function () {
                if (!validate([$('#snippet-group'), $('#snippet-scenario')])) {
                    return false;
                }
                else {
                    $('<input type="hidden" name="code"/>').val(code_section.getValue()).appendTo('#snippet-form');
                    $("#snippet-form").submit();
                }
            });

            $('#delete-snippet').on('click', function () {
                show_confirmation(
                    'Confirm Snippet Deletion',
                    'Are you sure? A deletion cannot be undone.',
                    'Delete',
                    'btn-danger'
                );
                return false;
            });

            get_confirmation(function(confirmed) {
                if (confirmed) {
                    $('#snippet-group').val(group_backup);
                    $('#snippet-scenario').val(scenario_backup);
                    snippet_form = $('#snippet-form');
                    snippet_form.attr('action', '/delete_snippet');
                    snippet_form.submit();
                }
            });
        });
    </script>
{% endblock %}